config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:show, :index, :create, :new] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :ingredient_id, :uniqueness => { :scope => :cocktail_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
require 'open-uri'

class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
    parse = @cocktail.name.downcase
    url = "https://www.thecocktaildb.com/api/json/v1/1/search.php?s=#{parse}"
    cocktail_db_serialized = open(url).read
    cocktail_db = JSON.parse(cocktail_db_serialized)
    @img_url = cocktail_db['drinks'][0]['strDrinkThumb']
    @category = cocktail_db['drinks'][0]['strCategory']
    @iba = cocktail_db['drinks'][0]['strIBA']
    @recipe = cocktail_db['drinks'][0]['strInstructions']
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @dose = Dose.new(dose_params)
    # we need `restaurant_id` to associate dose with corresponding restaurant
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktails_path
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<h1>+++++++ Cocktails +++++++</h1>
<br>

<p><%= link_to "Add cocktail", new_cocktail_path %></p>


<% @cocktails.each do |cocktail| %>
  <div class="cards">
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
      <%= cocktail.name %>
      <h3><%= link_to cocktail.name, cocktail_path(cocktail) %></h3>
    </div>
  </div>
<% end %>

app/views/cocktails/new.html.erb
<h2><%= "+++++++ Create your cocktail !! +++++++" %></h2>

<br>

<%= simple_form_for @cocktail do |f| %>

  <%= f.input :name %>
  <br>
  <%= f.submit %>

<% end %>

<p><%= link_to "Back to cocktails", cocktails_path %> ⏎</p>

app/views/cocktails/show.html.erb
<div class="card-product">
  <%= image_tag @img_url, alt: "alttext" %>
  <div class="card-product-infos">
    <h2><%= @cocktail.name %></h2>
    <p class="font-italic"><%= @iba %></p>
  </div>
</div>



<div class="d-flex justify-content-around">
<!--   <div class="cards">
 -->    <div class="card-category" style="">
      <h2><%= "Recipe" %></h2>
      <br>
      <ul>
        <% @cocktail.doses.each do |dose| %>
          <li>
            <p><%= dose.description %> - <%= dose.ingredient.name %> - <%= link_to "Remove ingredient", dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } %></p>
          </li>
        <% end %>
      </ul>
      <br>
      <p><%= link_to "Back to cocktails", cocktails_path %> ⏎</p>
    </div>

    <div class="card-category" style="">
      <h2>Add an ingredient</h2>
      <%= render "doses/new", cocktail: @cocktail, dose: @dose %>
      <br>
    </div>
  <!-- </div> -->
</div>

app/views/doses/_new.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>

  <%= f.association :ingredient %>

  <%= f.input :description %>
  <br>
  <%= f.submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">



  </head>

  <body>
    <%= yield %>
  </body>

</html>